context:
  workspace: "github-cloud-tedilabs-organization"
  organization: "tedilabs"

organization:
  name: tedilabs
  owners:
  - posquit0
  - tedilabs-dev
  blocked_users:
  - daangn-claud

teams:
  primary:
  - name: "Tedilabs"
    description: "All employees in Tedilabs"
    maintainers:
    - posquit0
  - name: "Bots"
    description: "A team for bot accounts in Tedilabs"
    is_secret: true
    members:
    - tedilabs-dev
  secondary:
  - name: "Chapter Android"
    description: "A chapter for android app developers in Tedilabs"
    parent_team: Tedilabs
    maintainers:
    - posquit0
  - name: "Chapter Backend"
    description: "A chapter for backend engineers in Tedilabs"
    parent_team: Tedilabs
    maintainers:
    - posquit0
  - name: "Chapter Data"
    description: "A chapter for data engineers in Tedilabs"
    parent_team: Tedilabs
    maintainers:
    - posquit0
  - name: "Chapter DBA"
    description: "A chapter for database administrators in Tedilabs"
    parent_team: Tedilabs
  - name: "Chapter iOS"
    description: "A chapter for iOS app developers in Tedilabs"
    parent_team: Tedilabs
  - name: "Chapter Web"
    description: "A chapter for web developers in Tedilabs"
    parent_team: Tedilabs
    maintainers:
    - posquit0
  - name: "Chapter Infra"
    description: "A chapter for infra engineers in Tedilabs"
    parent_team: Tedilabs
    maintainers:
    - posquit0
  - name: "Team DevOps"
    description: "A team for devops objective in Tedilabs"
    parent_team: Tedilabs
    maintainers:
    - posquit0

projects:
- name: "Roadmap for Terraform Modules"
  description: Roadmap for developing Terraform Modules
  columns:
  - Backlog
  - To-do
  - In Progress
  - In Review
  - Done
