context:
  workspace: "github-cloud-tedilabs-repositories"
  organization: "tedilabs"

remote_states:
  "organization":
    organization: "tedilabs"
    workspace: "github-cloud-tedilabs-organization"

repositories:
- name: .github
  description: 📣 Default community health files for @tedilabs organization on GitHub
  homepage: null
  visibility: public
  topics:
  - github
  - devops
  - sre
  permissions:
    admin:
      teams:
      - chapter-infra
- name: github
  description: ♥️  The best way to manage GitHub organization in @tedilabs
  homepage: null
  visibility: public
  topics:
  - lang-hcl
  - hcl2
  - iac
  - terraform
  - terraform-module
  - terraform-modules
  - terraform-github
  - github
  - github-organization
  - github-repository
  - github-team
  - devops
  - sre
  permissions:
    admin:
      teams:
      - chapter-infra
- name: api-docs-server
  description: ♥️  A web application to serve multiple API docs with Open API Specification
  homepage: null
  visibility: private
  topics:
  - lang-nodejs
  - swagger
  - redoc
  - oas
  - openapi
  - api-docs
  - api-docs
  - api-documentation
  - documentation-tool
  permissions:
    admin:
      teams:
      - chapter-infra
- name: dockerfiles
  description: 💾 A collection of useful Dockerfiles
  homepage: null
  visibility: public
  topics:
  - lang-dockerfile
  - dockerfile
  - dockerfiles
  - docker
  - docker-image
  permissions:
    admin:
      teams:
      - chapter-infra

## Kubernetes
- name: k8s-repository
  description: ♻️  Repository for Reusable Kubernetes App Manifests with Kustomize
  homepage: null
  visibility: public
  topics:
  - lang-yaml
  - k8s
  - kubernetes
  - kustomize
  - gitops
  - devops
  - sre
  permissions:
    admin:
      teams:
      - chapter-infra
      collaborators:
      - tedilabs-dev
- name: k8s-manifests
  description: ♥️  The best way to manage the kubernetes workloads in @tedilabs
  homepage: null
  visibility: private
  topics:
  - lang-yaml
  - k8s
  - kubernetes
  - kustomize
  - gitops
  - devops
  - sre
  permissions:
    admin:
      teams:
      - chapter-infra
      collaborators:
      - tedilabs-dev

## Terraform Modules
- name: terraform-aws-account
  description: 🌳 A sustainable Terraform Package which creates Account & IAM resources on AWS
  homepage: https://registry.terraform.io/modules/tedilabs/account/aws
  visibility: public
  topics:
  - lang-hcl
  - hcl2
  - iac
  - terraform
  - terraform-module
  - terraform-modules
  - terraform-aws
  - aws
  - aws-iam
  - aws-organization
  - aws-sso
  - devops
  - sre
  permissions:
    admin:
      teams:
      - chapter-infra
- name: terraform-aws-container
  description: 🌳 A sustainable Terraform Package which creates resources for Container Services on AWS
  homepage: https://registry.terraform.io/modules/tedilabs/container/aws
  visibility: public
  topics:
  - lang-hcl
  - hcl2
  - iac
  - terraform
  - terraform-module
  - terraform-modules
  - terraform-aws
  - aws
  - aws-ecr
  - aws-eks
  - devops
  - sre
  permissions:
    admin:
      teams:
      - chapter-infra
- name: terraform-aws-data
  description: 🌳 A sustainable Terraform Package which creates resources for Data Services on AWS
  homepage: https://registry.terraform.io/modules/tedilabs/data/aws
  visibility: public
  topics:
  - lang-hcl
  - hcl2
  - iac
  - terraform
  - terraform-module
  - terraform-modules
  - terraform-aws
  - aws
  - aws-athena
  - devops
  - sre
  permissions:
    admin:
      teams:
      - chapter-infra
- name: terraform-aws-domain
  description: 🌳 A sustainable Terraform Package which creates resources for Domain Services on AWS
  homepage: https://registry.terraform.io/modules/tedilabs/domain/aws
  visibility: public
  topics:
  - lang-hcl
  - hcl2
  - iac
  - terraform
  - terraform-module
  - terraform-modules
  - terraform-aws
  - aws
  - aws-route53
  - devops
  - sre
  permissions:
    admin:
      teams:
      - chapter-infra
- name: terraform-aws-ec2
  description: 🌳 A sustainable Terraform Package which creates resources for EC2 Services on AWS
  homepage: https://registry.terraform.io/modules/tedilabs/ec2/aws
  visibility: public
  topics:
  - lang-hcl
  - hcl2
  - iac
  - terraform
  - terraform-module
  - terraform-modules
  - terraform-aws
  - aws
  - aws-ec2
  - devops
  - sre
  permissions:
    admin:
      teams:
      - chapter-infra
- name: terraform-aws-firewall
  description: 🌳 A sustainable Terraform Package which creates resources for Firewall Services on AWS
  homepage: https://registry.terraform.io/modules/tedilabs/firewall/aws
  visibility: public
  topics:
  - lang-hcl
  - hcl2
  - iac
  - terraform
  - terraform-module
  - terraform-modules
  - terraform-aws
  - aws
  - aws-firewall
  - aws-waf
  - devops
  - sre
  permissions:
    admin:
      teams:
      - chapter-infra
- name: terraform-aws-load-balancer
  description: 🌳 A sustainable Terraform Package which creates resources for Load Balancers on AWS
  homepage: https://registry.terraform.io/modules/tedilabs/load-balancer/aws
  visibility: public
  topics:
  - lang-hcl
  - hcl2
  - iac
  - terraform
  - terraform-module
  - terraform-modules
  - terraform-aws
  - aws
  - aws-alb
  - aws-clb
  - aws-elb
  - aws-nlb
  - aws-load-balancer
  - devops
  - sre
  permissions:
    admin:
      teams:
      - chapter-infra
- name: terraform-aws-misc
  description: 🌳 A sustainable Terraform Package which creates MISC resources on AWS
  homepage: https://registry.terraform.io/modules/tedilabs/misc/aws
  visibility: public
  topics:
  - lang-hcl
  - hcl2
  - iac
  - terraform
  - terraform-module
  - terraform-modules
  - terraform-aws
  - aws
  - devops
  - sre
  permissions:
    admin:
      teams:
      - chapter-infra
- name: terraform-aws-ml
  description: 🌳 A sustainable Terraform Package which creates Machine Learning resources on AWS
  homepage: https://registry.terraform.io/modules/tedilabs/ml/aws
  visibility: public
  topics:
  - lang-hcl
  - hcl2
  - iac
  - terraform
  - terraform-module
  - terraform-modules
  - terraform-aws
  - aws
  - devops
  - sre
  permissions:
    admin:
      teams:
      - chapter-infra
- name: terraform-aws-network
  description: 🌳 A sustainable Terraform Package which creates Network resources on AWS
  homepage: https://registry.terraform.io/modules/tedilabs/network/aws
  visibility: public
  topics:
  - lang-hcl
  - hcl2
  - iac
  - terraform
  - terraform-module
  - terraform-modules
  - terraform-aws
  - aws
  - aws-dx
  - aws-privatelink
  - aws-vpc
  - aws-vpn
  - devops
  - sre
  permissions:
    admin:
      teams:
      - chapter-infra
- name: terraform-aws-secret
  description: 🌳 A sustainable Terraform Package which creates Secret resources on AWS
  homepage: https://registry.terraform.io/modules/tedilabs/secret/aws
  visibility: public
  topics:
  - lang-hcl
  - hcl2
  - iac
  - terraform
  - terraform-module
  - terraform-modules
  - terraform-aws
  - aws
  - aws-kms
  - aws-secrets-manager
  - aws-ssm-parameter-store
  - aws-parameter-store
  - devops
  - sre
  permissions:
    admin:
      teams:
      - chapter-infra
- name: terraform-aws-security
  description: 🌳 A sustainable Terraform Package which creates Security resources on AWS
  homepage: https://registry.terraform.io/modules/tedilabs/security/aws
  visibility: public
  topics:
  - lang-hcl
  - hcl2
  - iac
  - terraform
  - terraform-module
  - terraform-modules
  - terraform-aws
  - aws
  - aws-access-analyzer
  - aws-config
  - devops
  - sre
  permissions:
    admin:
      teams:
      - chapter-infra
- name: terraform-github-modules
  description: 🌳 A sustainable Terraform Package which manage all of things on GitHub
  homepage: https://registry.terraform.io/modules/tedilabs/modules/github
  visibility: public
  topics:
  - lang-hcl
  - hcl2
  - terraform
  - terraform-module
  - terraform-modules
  - github
  - devops
  - sre
  permissions:
    admin:
      teams:
      - chapter-infra
## Terraform Workspaces
- name: infrastructure
  description: ♥️  The best way to manage the infrastructure in @tedilabs
  homepage: null
  visibility: private
  topics:
  - lang-hcl
  - hcl2
  - iac
  - terraform
  - terraform-aws
  - aws
  - devops
  - sre
  permissions:
    admin:
      teams:
      - chapter-infra
- name: karrotpay-cb-infrastructure
  description: ♥️  The best way to manage the infrastructure of karrotpay sandbox account
  homepage: null
  visibility: private
  topics:
  - lang-hcl
  - hcl2
  - iac
  - terraform
  - terraform-aws
  - aws
  - devops
  - sre
  permissions:
    admin:
      teams:
      - chapter-infra
